project:
  type: book

book:
  title: "Lab Book"
  author: "Raphael Angerbauer"
  date: "3/1/24"
  chapters:
    - index.qmd
    - 'Styx.ipynb'
    - references.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc-depth: 3
    number-depth: 4
    execture:
      echo: false



